/*
 * 自动生成 —— 不要手改。见 tools/gen-api-coverage.py。
 *
 * 调用 ticode 每个 public static 方法一次，供 javac 校验全部 API 签名。
 * 只编译、不运行（许多方法依赖 Android 运行时）。
 */
public class ApiCoverage {
  // throws Exception：部分 ticode 方法声明了受检异常（IOException 等）
  public static void all() throws Exception {
    ticode.zh.android.Java代码扩展.三元判断((boolean)false, (Object)null, (Object)null);
    ticode.zh.android.Java代码扩展.三元判断赋值((Object)null, (boolean)false, (Object)null, (Object)null);
    ticode.zh.android.ROOT操作.免ROOT执行二进制文件((android.content.Context)null, (String)null, (String[])null, (String)null);
    ticode.zh.android.ROOT操作.执行ROOT命令((String)null, (String[])null, (String)null);
    ticode.zh.android.ROOT操作.执行二进制文件((String)null, (String[])null, (String)null);
    ticode.zh.android.ROOT操作.执行命令((String)null, (String[])null, (String)null);
    ticode.zh.android.ROOT操作.是否ROOT();
    ticode.zh.android.ROOT操作.获取ROOT();
    ticode.zh.android.RSA密钥对.创建RSA密钥对((int)0);
    ticode.zh.android._屏幕方向监听服务.startService((android.content.Context)null, (Class<?>)null);
    ticode.zh.android._屏幕方向监听服务.stopService((android.content.Context)null, (Class<?>)null);
    ticode.zh.android._屏幕方向监听服务.停止服务((android.content.Context)null);
    ticode.zh.android._屏幕方向监听服务.启动服务((android.content.Context)null);
    ticode.zh.android._悬浮窗_权限申请窗口.isPermission((android.content.Context)null);
    ticode.zh.android._悬浮窗_权限申请窗口.requestPermission((android.content.Context)null, (ticode.zh.android._悬浮窗_权限申请窗口.FPListener)null);
    ticode.zh.android._悬浮窗_权限申请窗口.toSetting((android.content.Context)null);
    ticode.zh.android._悬浮窗_权限申请窗口.toSetting2((android.content.Context)null);
    ticode.zh.android.位图对象.从字节集创建位图(new byte[0], (int)0, (int)0);
    ticode.zh.android.位图对象.从文件路径创建位图((String)null);
    ticode.zh.android.位图对象.从资源文件创建位图((android.content.Context)null, (String)null);
    ticode.zh.android.位图对象.从输入流创建位图((ticode.zh.jvm.输入流)null);
    ticode.zh.android.位图对象.创建位图((android.graphics.Bitmap)null);
    ticode.zh.android.位图对象.创建位图2((int)0, (int)0, (android.graphics.Bitmap.Config)null);
    ticode.zh.android.位图对象.创建位图3((int)0, (int)0, (android.graphics.Bitmap.Config)null, (boolean)false);
    ticode.zh.android.位图对象.创建位图4(new int[0], (int)0, (int)0, (android.graphics.Bitmap.Config)null);
    ticode.zh.android.位图对象.创建位图5((ticode.zh.android.可绘制对象)null, (android.graphics.Bitmap.Config)null);
    ticode.zh.android.位图对象.创建缩放位图((android.graphics.Bitmap)null, (int)0, (int)0, (boolean)false);
    ticode.zh.android.位图对象.放大图片((android.graphics.Bitmap)null, (int)0);
    ticode.zh.android.位图配置.到配置((String)null);
    ticode.zh.android.位图配置.配置列表();
    ticode.zh.android.位运算.位与((int)0, (int)0);
    ticode.zh.android.位运算.位右移((int)0, (int)0);
    ticode.zh.android.位运算.位左移((int)0, (int)0);
    ticode.zh.android.位运算.位异或((int)0, (int)0);
    ticode.zh.android.位运算.位或((int)0, (int)0);
    ticode.zh.android.位运算.位非((int)0);
    ticode.zh.android.位运算.无符号位右移((int)0, (int)0);
    ticode.zh.android.信使.新建对象((ticode.zh.android.消息处理器)null);
    ticode.zh.android.信使.新建对象2((android.os.IBinder)null);
    ticode.zh.android.偏移动画.新建((double)0, (double)0, (double)0, (double)0);
    ticode.zh.android.像素操作.DP到PX((int)0);
    ticode.zh.android.像素操作.PX到DP((int)0);
    ticode.zh.android.像素操作.PX到SP((int)0);
    ticode.zh.android.像素操作.SP到PX((int)0);
    ticode.zh.android.共享数据.初始化((android.content.Context)null, (String)null);
    ticode.zh.android.共享数据.包含数据((String)null);
    ticode.zh.android.共享数据.取整数((String)null, (int)0);
    ticode.zh.android.共享数据.取文本((String)null, (String)null);
    ticode.zh.android.共享数据.取逻辑值((String)null, (boolean)false);
    ticode.zh.android.共享数据.清空();
    ticode.zh.android.共享数据.置整数((String)null, (int)0);
    ticode.zh.android.共享数据.置文本((String)null, (String)null);
    ticode.zh.android.共享数据.置逻辑值((String)null, (boolean)false);
    ticode.zh.android.加解密操作.AES加密((String)null, (String)null, (String)null);
    ticode.zh.android.加解密操作.AES解密((String)null, (String)null, (String)null);
    ticode.zh.android.加解密操作.Base64_到二进制(new byte[0], (int)0);
    ticode.zh.android.加解密操作.Base64编码((String)null, (String)null, (String)null);
    ticode.zh.android.加解密操作.Base64编码_字节集(new byte[0], (String)null);
    ticode.zh.android.加解密操作.Base64解码((String)null, (String)null, (String)null);
    ticode.zh.android.加解密操作.Base64解码_字节集((String)null, (String)null);
    ticode.zh.android.加解密操作.DES加密((String)null, (String)null, (String)null);
    ticode.zh.android.加解密操作.DES解密((String)null, (String)null, (String)null);
    ticode.zh.android.加解密操作.HexString2Bytes((String)null, (String)null);
    ticode.zh.android.加解密操作.MD5加密((String)null, (String)null);
    ticode.zh.android.加解密操作.RC4Base(new byte[0], (String)null, (String)null);
    ticode.zh.android.加解密操作.RC4加密((String)null, (String)null, (String)null);
    ticode.zh.android.加解密操作.RC4解密((String)null, (String)null, (String)null);
    ticode.zh.android.加解密操作.RSA加密((String)null, (String)null, (String)null);
    ticode.zh.android.加解密操作.RSA解密((String)null, (String)null, (String)null);
    ticode.zh.android.加解密操作.SHA加密((String)null, (String)null);
    ticode.zh.android.加解密操作.initKey((String)null, (String)null);
    ticode.zh.android.加解密操作.uniteBytes((byte)0, (byte)0);
    ticode.zh.android.压缩操作.ZIP压缩((String)null, (String)null);
    ticode.zh.android.压缩操作.ZIP解压((String)null, (String)null);
    ticode.zh.android.可绘制对象.从文件流创建((ticode.zh.jvm.文件输入流)null, (String)null);
    ticode.zh.android.可绘制对象.从路径创建((String)null);
    ticode.zh.android.图片操作.Bitmap2Bytes((android.graphics.Bitmap)null);
    ticode.zh.android.图片操作.Bytes2Bitmap(new byte[0]);
    ticode.zh.android.图片操作.倾斜图片(new byte[0], (double)0, (double)0);
    ticode.zh.android.图片操作.切割图片(new byte[0], (int)0, (int)0);
    ticode.zh.android.图片操作.压缩图片(new byte[0]);
    ticode.zh.android.图片操作.压缩图片2((String)null, (String)null, (int)0);
    ticode.zh.android.图片操作.反转图片(new byte[0], (int)0);
    ticode.zh.android.图片操作.取图片字节数组((String)null, (android.content.Context)null);
    ticode.zh.android.图片操作.取图片宽度((android.content.Context)null, (String)null);
    ticode.zh.android.图片操作.取图片宽度2(new byte[0]);
    ticode.zh.android.图片操作.取图片部分(new byte[0], (int)0, (int)0, (int)0, (int)0);
    ticode.zh.android.图片操作.取图片高度((android.content.Context)null, (String)null);
    ticode.zh.android.图片操作.取图片高度2(new byte[0]);
    ticode.zh.android.图片操作.旋转图片(new byte[0], (double)0);
    ticode.zh.android.图片操作.更新系统相册((android.content.Context)null, (String)null);
    ticode.zh.android.图片操作.缩放图片(new byte[0], (int)0, (int)0);
    ticode.zh.android.图片操作.设置图片倒影(new byte[0]);
    ticode.zh.android.图片操作.设置图片圆角(new byte[0], (int)0);
    ticode.zh.android.字体对象.从文件路径创建字体((String)null);
    ticode.zh.android.字体对象.从资源文件创建字体((ticode.zh.android.安卓窗口)null, (String)null);
    ticode.zh.android.存储卡操作.取CPU主频();
    ticode.zh.android.存储卡操作.取内部存储卡剩余容量();
    ticode.zh.android.存储卡操作.取内部存储卡总容量();
    ticode.zh.android.存储卡操作.取存储卡剩余容量();
    ticode.zh.android.存储卡操作.取存储卡总容量();
    ticode.zh.android.存储卡操作.取存储卡状态();
    ticode.zh.android.存储卡操作.取存储卡路径();
    ticode.zh.android.存储卡操作.取手机剩余内存((android.content.Context)null);
    ticode.zh.android.存储卡操作.取手机总内存();
    ticode.zh.android.存储卡操作.存储卡是否可写();
    ticode.zh.android.安卓应用.取安卓应用();
    ticode.zh.android.安卓提示框.弹出提示((android.content.Context)null, (String)null, (boolean)false);
    ticode.zh.android.安卓提示框.新建提示框((android.content.Context)null);
    ticode.zh.android.安卓程序签名数据.从文本创建((String)null);
    ticode.zh.android.安卓窗口.newActivity((android.app.Activity)null, (Class<?>)null);
    ticode.zh.android.安卓窗口.newActivity2((android.app.Activity)null, (Class<?>)null, (android.content.Intent)null);
    ticode.zh.android.安卓窗口.newActivityForResult((android.app.Activity)null, (Class<?>)null, (int)0);
    ticode.zh.android.安卓窗口.newActivityForResult2((android.app.Activity)null, (Class<?>)null, (int)0, (android.content.Intent)null);
    ticode.zh.android.安卓线程.取当前线程();
    ticode.zh.android.安卓线程.取当前线程ID();
    ticode.zh.android.安卓线程.取当前线程名称();
    ticode.zh.android.安卓线程.延时((long)0);
    ticode.zh.android.安卓线程.转交其它线程执行();
    ticode.zh.android.安卓资源标识符.从文件创建((java.io.File)null);
    ticode.zh.android.安卓资源标识符.文本到Uri编码((String)null);
    ticode.zh.android.安卓资源标识符.文本到Uri解码((String)null);
    ticode.zh.android.安卓资源标识符.解析((String)null);
    ticode.zh.android.安卓资源标识符.赋值_op((String)null);
    ticode.zh.android.对象操作.写出对象((Object)null, (String)null);
    ticode.zh.android.对象操作.哈希表((ticode.zh.jvm.键值对[])null);
    ticode.zh.android.对象操作.新建对象((String)null);
    ticode.zh.android.对象操作.新建窗口组件((String)null, (android.content.Context)null);
    ticode.zh.android.对象操作.读入对象((String)null);
    ticode.zh.android.对象操作.键值对((Object)null, (Object)null);
    ticode.zh.android.局域网工具.IP地址是否连通((String)null, (int)0);
    ticode.zh.android.局域网工具.IP地址是否连通_同步((String)null, (int)0);
    ticode.zh.android.局域网工具.是否开启网络代理();
    ticode.zh.android.局域网工具.端口是否开放((int)0, (String)null, (int)0);
    ticode.zh.android.局域网工具.端口是否开放_同步((int)0, (String)null, (int)0);
    ticode.zh.android.局域网工具.获取本机IP地址();
    ticode.zh.android.常用操作.调试输出((Object)null);
    ticode.zh.android.常用操作.调试输出2((String)null, (Object[])null);
    ticode.zh.android.常用操作.运行报错((String)null);
    ticode.zh.android.应用操作.卸载应用((android.content.Context)null, (String)null);
    ticode.zh.android.应用操作.安装应用((android.content.Context)null, (String)null);
    ticode.zh.android.应用操作.应用是否已安装((android.content.Context)null, (String)null);
    ticode.zh.android.应用操作.打开应用((android.content.Context)null, (String)null);
    ticode.zh.android.应用操作.打开应用信息页((android.content.Context)null, (String)null);
    ticode.zh.android.悬浮窗.createFloatingWindow((String)null, (android.view.View)null);
    ticode.zh.android.悬浮窗.getAllFWindow();
    ticode.zh.android.悬浮窗.getFWindow((String)null);
    ticode.zh.android.悬浮窗.关闭所有悬浮窗();
    ticode.zh.android.悬浮窗.关闭指定悬浮窗((String)null);
    ticode.zh.android.悬浮窗.创建悬浮窗((ticode.zh.android.组件容器)null, (String)null);
    ticode.zh.android.悬浮窗.取悬浮窗((String)null);
    ticode.zh.android.悬浮窗.取所有悬浮窗();
    ticode.zh.android.悬浮窗.是否存在悬浮窗((String)null);
    ticode.zh.android.悬浮窗.显示指定悬浮窗((String)null);
    ticode.zh.android.悬浮窗.隐藏指定悬浮窗((String)null);
    ticode.zh.android.拼音操作.取汉字拼音((String)null);
    ticode.zh.android.拼音操作.取汉字首拼((String)null);
    ticode.zh.android.拼音操作.取词组拼音((String)null);
    ticode.zh.android.拼音操作.取词组首拼((String)null);
    ticode.zh.android.提示框.弹出提示((android.content.Context)null, (String)null, (boolean)false);
    ticode.zh.android.数学运算.取余((int)0, (int)0);
    ticode.zh.android.数学运算.取最大值((double)0, (double)0);
    ticode.zh.android.数学运算.取最小值((double)0, (double)0);
    ticode.zh.android.数学运算.取符号((double)0);
    ticode.zh.android.数学运算.取绝对值((double)0);
    ticode.zh.android.数学运算.取随机小数((double)0, (double)0);
    ticode.zh.android.数学运算.取随机数((int)0, (int)0);
    ticode.zh.android.数学运算.向下取整((double)0);
    ticode.zh.android.数学运算.向下取整_整数值((double)0);
    ticode.zh.android.数学运算.四舍五入((double)0, (int)0);
    ticode.zh.android.数学运算.弧度转角度((double)0);
    ticode.zh.android.数学运算.求余弦((double)0);
    ticode.zh.android.数学运算.求反余弦((double)0);
    ticode.zh.android.数学运算.求反对数((double)0);
    ticode.zh.android.数学运算.求反正切((double)0);
    ticode.zh.android.数学运算.求反正弦((double)0);
    ticode.zh.android.数学运算.求平方根((double)0);
    ticode.zh.android.数学运算.求次方((double)0, (double)0);
    ticode.zh.android.数学运算.求次方根((double)0, (double)0);
    ticode.zh.android.数学运算.求正切((double)0);
    ticode.zh.android.数学运算.求正弦((double)0);
    ticode.zh.android.数学运算.求自然对数((double)0);
    ticode.zh.android.数学运算.角度转弧度((double)0);
    ticode.zh.android.数学运算.计算表达式((String)null);
    ticode.zh.android.数据库.删除数据库((String)null);
    ticode.zh.android.数据库.打开数据库((String)null);
    ticode.zh.android.数组操作.取数组最大数(new int[0]);
    ticode.zh.android.数组操作.取数组长度((Object[])null);
    ticode.zh.android.数组操作.取数组长度(new byte[0]);
    ticode.zh.android.数组操作.数组冒泡排序(new int[0]);
    ticode.zh.android.数组操作.数组到文本((Object)null);
    ticode.zh.android.数组操作.数组到文本2((Object)null);
    ticode.zh.android.数组操作.数组到集合((Object[])null);
    ticode.zh.android.文件操作.append((java.io.File)null, (String)null);
    ticode.zh.android.文件操作.append((java.io.File)null, new byte[0]);
    ticode.zh.android.文件操作.append((java.io.File)null, new byte[0], (int)0, (int)0);
    ticode.zh.android.文件操作.convertFileSize((long)0, (int)0);
    ticode.zh.android.文件操作.copyTo((java.io.File)null, (java.io.File)null);
    ticode.zh.android.文件操作.createDirectory((java.io.File)null);
    ticode.zh.android.文件操作.createFile((java.io.File)null);
    ticode.zh.android.文件操作.deleteFile((java.io.File)null);
    ticode.zh.android.文件操作.getFileName((String)null);
    ticode.zh.android.文件操作.getFilePath((String)null);
    ticode.zh.android.文件操作.getMD5((java.io.File)null);
    ticode.zh.android.文件操作.getSHA1((java.io.File)null);
    ticode.zh.android.文件操作.moveTo((java.io.File)null, (java.io.File)null);
    ticode.zh.android.文件操作.searchByName((java.io.File)null, (String)null, (boolean)false, (boolean)false, (boolean)false);
    ticode.zh.android.文件操作.write((java.io.File)null, (String)null);
    ticode.zh.android.文件操作.write((java.io.File)null, new byte[0]);
    ticode.zh.android.文件操作.write((java.io.File)null, new byte[0], (int)0, (int)0);
    ticode.zh.android.文件操作.关闭写();
    ticode.zh.android.文件操作.关闭读();
    ticode.zh.android.文件操作.写一行((String)null);
    ticode.zh.android.文件操作.写出字节文件((String)null, new byte[0]);
    ticode.zh.android.文件操作.写出文本文件((String)null, (String)null);
    ticode.zh.android.文件操作.写出资源文件((android.content.Context)null, (String)null, (String)null);
    ticode.zh.android.文件操作.创建文件((String)null);
    ticode.zh.android.文件操作.创建目录((String)null);
    ticode.zh.android.文件操作.删除文件((String)null);
    ticode.zh.android.文件操作.取子文件列表((String)null);
    ticode.zh.android.文件操作.取子文件列表2((String)null, (int)0, (boolean)false);
    ticode.zh.android.文件操作.取子文件集合((String)null);
    ticode.zh.android.文件操作.取子文件集合2((String)null, (int)0, (boolean)false);
    ticode.zh.android.文件操作.取子目录((String)null);
    ticode.zh.android.文件操作.取所有文件路径((String)null, (java.util.List<String>)null);
    ticode.zh.android.文件操作.取文件CRC32((String)null);
    ticode.zh.android.文件操作.取文件MD5((String)null);
    ticode.zh.android.文件操作.取文件SHA1((String)null);
    ticode.zh.android.文件操作.取文件修改时间((String)null);
    ticode.zh.android.文件操作.取文件前缀名((String)null);
    ticode.zh.android.文件操作.取文件名((String)null);
    ticode.zh.android.文件操作.取文件后缀名((String)null);
    ticode.zh.android.文件操作.取文件哈希值((String)null);
    ticode.zh.android.文件操作.取文件大小((String)null);
    ticode.zh.android.文件操作.取文件大小2((String)null);
    ticode.zh.android.文件操作.取文件编码((String)null);
    ticode.zh.android.文件操作.复制文件((String)null, (String)null);
    ticode.zh.android.文件操作.寻找文件关键词((String)null, (String)null);
    ticode.zh.android.文件操作.寻找文件后缀名((String)null, (String)null);
    ticode.zh.android.文件操作.打开文本文件_写((String)null, (String)null);
    ticode.zh.android.文件操作.打开文本文件_读((String)null, (String)null);
    ticode.zh.android.文件操作.文件是否存在((String)null);
    ticode.zh.android.文件操作.是否为目录((String)null);
    ticode.zh.android.文件操作.是否为隐藏文件((String)null);
    ticode.zh.android.文件操作.移动文件((String)null, (String)null);
    ticode.zh.android.文件操作.读一行();
    ticode.zh.android.文件操作.读入文件字节((String)null);
    ticode.zh.android.文件操作.读入文本文件((String)null, (String)null);
    ticode.zh.android.文件操作.读入资源文件((android.content.Context)null, (String)null, (String)null);
    ticode.zh.android.文件操作.转换文件大小((String)null, (int)0);
    ticode.zh.android.文件操作.转换文件大小2((String)null, (int)0);
    ticode.zh.android.文件操作.追加文件内容((String)null, (String)null);
    ticode.zh.android.文件操作.重命名文件((String)null, (String)null);
    ticode.zh.android.文本操作.格式化文本((String)null, (Object[])null);
    ticode.zh.android.旋转动画.新建((double)0, (double)0);
    ticode.zh.android.旋转动画.新建2((double)0, (double)0, (double)0, (double)0);
    ticode.zh.android.时间操作.取当前时间戳();
    ticode.zh.android.时间操作.取当前纳秒时间戳();
    ticode.zh.android.时间操作.取格式时间((String)null);
    ticode.zh.android.时间操作.取相对纳秒时间戳();
    ticode.zh.android.时间操作.时间戳到文本((long)0, (String)null);
    ticode.zh.android.时间操作.时间文本到时间戳((String)null, (String)null);
    ticode.zh.android.构建路径.创建路径();
    ticode.zh.android.样式_上标.取实例();
    ticode.zh.android.样式_下划线.取实例();
    ticode.zh.android.样式_下标.取实例();
    ticode.zh.android.样式_删除线.取实例();
    ticode.zh.android.样式_前景色.取实例((int)0);
    ticode.zh.android.样式_字体大小.取实例((android.content.Context)null, (int)0);
    ticode.zh.android.样式_字体样式.取实例((int)0);
    ticode.zh.android.样式_背景色.取实例((int)0);
    ticode.zh.android.流程处理.为调试版();
    ticode.zh.android.流程处理.俘获所有异常();
    ticode.zh.android.流程处理.取俘获异常();
    ticode.zh.android.流程处理.取反((boolean)false);
    ticode.zh.android.流程处理.取当前源文件路径();
    ticode.zh.android.流程处理.取当前行号();
    ticode.zh.android.流程处理.取构建时间();
    ticode.zh.android.流程处理.取构建时间戳();
    ticode.zh.android.流程处理.容错处理();
    ticode.zh.android.流程处理.容错运行((Object)null);
    ticode.zh.android.流程处理.开始俘获异常();
    ticode.zh.android.流程处理.提交主线程任务((ticode.zh.android.可执行任务)null, (long)0);
    ticode.zh.android.流程处理.提交到主线程运行((ticode.zh.android.安卓窗口)null);
    ticode.zh.android.流程处理.提交到主线程运行2();
    ticode.zh.android.流程处理.提交到新线程运行();
    ticode.zh.android.流程处理.是否处于主线程();
    ticode.zh.android.流程处理.移除主线程任务((ticode.zh.android.可执行任务)null);
    ticode.zh.android.流程处理.等待新线程执行完毕();
    ticode.zh.android.流程处理.结束俘获异常();
    ticode.zh.android.流程处理.结束容错();
    ticode.zh.android.流程处理.结束提交到主线程();
    ticode.zh.android.流程处理.结束提交到新线程();
    ticode.zh.android.流程处理.自乘((int)0, (int)0);
    ticode.zh.android.流程处理.自减((int)0, (int)0);
    ticode.zh.android.流程处理.自增((int)0, (int)0);
    ticode.zh.android.流程处理.自除((int)0, (int)0);
    ticode.zh.android.流程处理.赋值((Object)null, (Object)null);
    ticode.zh.android.消息.获取消息((ticode.zh.android.消息处理器)null, (int)0);
    ticode.zh.android.画布对象.创建画布((android.graphics.Bitmap)null);
    ticode.zh.android.画笔对象.创建画笔();
    ticode.zh.android.程序崩溃处理.初始化((android.content.Context)null, (String)null);
    ticode.zh.android.系统操作.优化内存();
    ticode.zh.android.系统操作.关闭程序();
    ticode.zh.android.系统操作.创建硬链接((String)null, (String)null);
    ticode.zh.android.系统操作.创建软链接((String)null, (String)null);
    ticode.zh.android.系统操作.删除环境变量((String)null);
    ticode.zh.android.系统操作.加载SO库((String)null);
    ticode.zh.android.系统操作.取ANDROID_ID((ticode.zh.android.安卓窗口)null);
    ticode.zh.android.系统操作.取剪切板文本((android.content.Context)null);
    ticode.zh.android.系统操作.取导航栏高度((android.content.Context)null);
    ticode.zh.android.系统操作.取屏幕刷新率((android.content.Context)null);
    ticode.zh.android.系统操作.取屏幕宽度((android.content.Context)null);
    ticode.zh.android.系统操作.取屏幕密度((android.content.Context)null);
    ticode.zh.android.系统操作.取屏幕最大刷新率((ticode.zh.android.安卓窗口)null);
    ticode.zh.android.系统操作.取屏幕高度((android.content.Context)null);
    ticode.zh.android.系统操作.取屏幕高度_不含导航栏((android.content.Context)null);
    ticode.zh.android.系统操作.取屏幕高度_不含导航栏和状态栏((android.content.Context)null);
    ticode.zh.android.系统操作.取父进程ID();
    ticode.zh.android.系统操作.取状态栏高度((android.content.Context)null);
    ticode.zh.android.系统操作.取环境变量((String)null);
    ticode.zh.android.系统操作.取用户ID();
    ticode.zh.android.系统操作.取系统属性((String)null);
    ticode.zh.android.系统操作.取设备唯一标识符();
    ticode.zh.android.系统操作.取软链接指向文件((String)null);
    ticode.zh.android.系统操作.取进程ID();
    ticode.zh.android.系统操作.导航栏是否显示((android.content.Context)null);
    ticode.zh.android.系统操作.截屏((ticode.zh.android.安卓窗口)null, (String)null);
    ticode.zh.android.系统操作.截屏_位图((ticode.zh.android.安卓窗口)null);
    ticode.zh.android.系统操作.清除系统属性((String)null);
    ticode.zh.android.系统操作.禁止截屏((ticode.zh.android.窗口)null);
    ticode.zh.android.系统操作.置剪切板文本((android.content.Context)null, (String)null);
    ticode.zh.android.系统操作.置屏幕刷新率((ticode.zh.android.安卓窗口)null, (int)0);
    ticode.zh.android.系统操作.置文件权限((String)null, (int)0);
    ticode.zh.android.系统操作.置环境变量((String)null, (String)null, (boolean)false);
    ticode.zh.android.系统操作.置系统属性((String)null, (String)null);
    ticode.zh.android.组件动画集合.新建集合();
    ticode.zh.android.组件样式操作.渐变((ticode.zh.android.可视化组件)null, new int[0], (android.graphics.drawable.GradientDrawable.Orientation)null, (int)0, (int)0, (int)0, (int)0);
    ticode.zh.android.组件样式操作.置圆背景2((ticode.zh.android.可视化组件)null, (int)0, (double)0);
    ticode.zh.android.组件样式操作.置圆角((ticode.zh.android.可视化组件)null, (double)0, (double)0, (double)0, (double)0);
    ticode.zh.android.组件样式操作.置圆角背景((ticode.zh.android.可视化组件)null, (int)0, (double)0, (double)0, (double)0, (double)0);
    ticode.zh.android.组件样式操作.置圆角背景边框((ticode.zh.android.可视化组件)null, (int)0, (int)0, (int)0, (double)0, (double)0, (double)0, (double)0);
    ticode.zh.android.组件样式操作.置圆角背景边框2((ticode.zh.android.可视化组件)null, (int)0, (int)0, (int)0, (double)0);
    ticode.zh.android.组件样式操作.置圆角边框((ticode.zh.android.可视化组件)null, (int)0, (int)0, (double)0, (double)0, (double)0, (double)0);
    ticode.zh.android.组件样式操作.置圆角边框2((ticode.zh.android.可视化组件)null, (int)0, (int)0, (double)0);
    ticode.zh.android.组件样式操作.置普通样式((ticode.zh.android.可视化组件)null, (double)0, (int)0, (int)0);
    ticode.zh.android.组件样式操作.置水波纹样式((ticode.zh.android.可视化组件)null, (double)0, (int)0, (int)0);
    ticode.zh.android.组件样式操作.置水波纹样式2((ticode.zh.android.可视化组件)null, (int)0);
    ticode.zh.android.组件样式操作.置水波纹样式3((ticode.zh.android.可视化组件)null, (float)0, (int)0);
    ticode.zh.android.编码操作.UCS2编码((String)null);
    ticode.zh.android.编码操作.UCS2解码((String)null);
    ticode.zh.android.编码操作.URL编码((String)null, (String)null);
    ticode.zh.android.编码操作.URL解码((String)null, (String)null);
    ticode.zh.android.编码操作.二进制到文本((String)null);
    ticode.zh.android.编码操作.十六进制到文本((String)null, (String)null);
    ticode.zh.android.编码操作.文本到二进制((String)null, (String)null);
    ticode.zh.android.编码操作.文本到十六进制((String)null, (String)null);
    ticode.zh.android.编码操作.转换编码((String)null, (String)null, (String)null);
    ticode.zh.android.缩放动画.新建((double)0, (double)0, (double)0, (double)0);
    ticode.zh.android.网络请求.GET同步请求((String)null, (String)null, (String)null);
    ticode.zh.android.网络请求.GET异步请求((String)null, (String)null, (String)null);
    ticode.zh.android.网络请求.POST同步请求((String)null, (String)null, (String)null);
    ticode.zh.android.网络请求.POST异步请求((String)null, (String)null, (String)null);
    ticode.zh.android.网络请求.POST提交数据((Object)null);
    ticode.zh.android.网络请求.httpRequest((ticode.zh.android.网络请求结果)null, (String)null, (String)null, (String)null, (String)null);
    ticode.zh.android.网络请求.readStream((java.io.InputStream)null);
    ticode.zh.android.网络请求.取网络请求GZIP压缩();
    ticode.zh.android.网络请求.取网络请求结果();
    ticode.zh.android.网络请求.取网络请求超时();
    ticode.zh.android.网络请求.添加网络请求头((String)null, (String)null);
    ticode.zh.android.网络请求.清除网络请求头();
    ticode.zh.android.网络请求.移除网络请求头((String)null);
    ticode.zh.android.网络请求.结束网络请求();
    ticode.zh.android.网络请求.置网络请求GZIP压缩((boolean)false);
    ticode.zh.android.网络请求.置网络请求超时((int)0);
    ticode.zh.android.转换操作.Unicode转中文((String)null);
    ticode.zh.android.转换操作.中文转Unicode((String)null);
    ticode.zh.android.转换操作.十六进制到字节集((String)null);
    ticode.zh.android.转换操作.字节到整数(new byte[0]);
    ticode.zh.android.转换操作.字节到文本(new byte[0], (String)null);
    ticode.zh.android.转换操作.字节到长整数(new byte[0]);
    ticode.zh.android.转换操作.字节集到十六进制(new byte[0]);
    ticode.zh.android.转换操作.字节集到整数(new byte[0]);
    ticode.zh.android.转换操作.字节集到文本(new byte[0], (String)null);
    ticode.zh.android.转换操作.字节集到长整数(new byte[0]);
    ticode.zh.android.转换操作.对象到文本((Object)null);
    ticode.zh.android.转换操作.数值到金额((double)0);
    ticode.zh.android.转换操作.整数到字节((int)0);
    ticode.zh.android.转换操作.整数到字节集((int)0);
    ticode.zh.android.转换操作.文本到字节((String)null, (String)null);
    ticode.zh.android.转换操作.文本到字节集((String)null, (String)null);
    ticode.zh.android.转换操作.长整数到字节((long)0);
    ticode.zh.android.转换操作.长整数到字节集((long)0);
    ticode.zh.android.软件配置.允许更改窗口大小();
    ticode.zh.android.软件配置.开启硬件加速();
    ticode.zh.android.软件配置.申请更大内存();
    ticode.zh.android.软件配置.禁止更改窗口大小();
    ticode.zh.android.软件配置.置最低安卓版本((int)0);
    ticode.zh.android.软件配置.置版本号((int)0);
    ticode.zh.android.软件配置.置版本名称((String)null);
    ticode.zh.android.软件配置.置目标安卓版本((int)0);
    ticode.zh.android.软件配置.置软件名称((String)null);
    ticode.zh.android.软件配置.置软件图标((String)null);
    ticode.zh.android.透明动画.新建((double)0, (double)0);
    ticode.zh.android.通知栏.关闭所有通知栏();
    ticode.zh.android.通知栏.创建通知栏((android.content.Context)null);
    ticode.zh.android.震动操作.震动((android.content.Context)null, (long)0);
    ticode.zh.android.预备启动信息.取前台服务((android.content.Context)null, (int)0, (android.content.Intent)null, (int)0);
    ticode.zh.android.预备启动信息.取安卓窗口((android.content.Context)null, (int)0, (android.content.Intent)null, (int)0);
    ticode.zh.android.预备启动信息.取广播((android.content.Context)null, (int)0, (android.content.Intent)null, (int)0);
    ticode.zh.android.预备启动信息.取服务((android.content.Context)null, (int)0, (android.content.Intent)null, (int)0);
    ticode.zh.android.颜色操作.RGBtoHSV(new int[0]);
    ticode.zh.android.颜色操作.修改颜色红色值((int)0, (int)0);
    ticode.zh.android.颜色操作.修改颜色绿色值((int)0, (int)0);
    ticode.zh.android.颜色操作.修改颜色蓝色值((int)0, (int)0);
    ticode.zh.android.颜色操作.修改颜色透明度((int)0, (int)0);
    ticode.zh.android.颜色操作.取灰度值((int)0);
    ticode.zh.android.颜色操作.取随机颜色((boolean)false);
    ticode.zh.android.颜色操作.取颜色亮度((int)0);
    ticode.zh.android.颜色操作.取颜色红色值((int)0);
    ticode.zh.android.颜色操作.取颜色绿色值((int)0);
    ticode.zh.android.颜色操作.取颜色色相((int)0);
    ticode.zh.android.颜色操作.取颜色蓝色值((int)0);
    ticode.zh.android.颜色操作.取颜色透明度((int)0);
    ticode.zh.android.颜色操作.取颜色饱和度((int)0);
    ticode.zh.android.颜色操作.合成颜色值((int)0, (int)0, (int)0, (int)0);
    ticode.zh.android.颜色操作.文本到颜色值((String)null);
    ticode.zh.android.颜色操作.文本到颜色值_自定义格式((String)null, (int)0);
    ticode.zh.android.颜色操作.是否为浅色((int)0);
    ticode.zh.android.颜色操作.颜色值到文本((int)0, (boolean)false, (boolean)false);
    ticode.zh.android.颜色操作.颜色值到文本_自定义格式((int)0, (boolean)false, (int)0);
    ticode.zh.android.颜色操作.颜色加深((int)0, (int)0);
    ticode.zh.android.颜色操作.颜色变浅((int)0, (int)0);
    ticode.zh.base.单精度小数.到整数((float)0);
    ticode.zh.base.字符.为大写字母((char)0);
    ticode.zh.base.字符.为字母((char)0);
    ticode.zh.base.字符.为字母或数字((char)0);
    ticode.zh.base.字符.为小写字母((char)0);
    ticode.zh.base.字符.为数字((char)0);
    ticode.zh.base.字符.为空格((char)0);
    ticode.zh.base.字符.到大写字母((char)0);
    ticode.zh.base.字符.到小写字母((char)0);
    ticode.zh.base.字符.到整数((char)0);
    ticode.zh.base.字节.到整数((byte)0);
    ticode.zh.base.小数.到整数((double)0);
    ticode.zh.base.异步调度类.back((Runnable)null);
    ticode.zh.base.异步调度类.launch((Runnable)null);
    ticode.zh.base.异步调度类.shutdown();
    ticode.zh.base.整数.到二进制((int)0);
    ticode.zh.base.整数.到八进制((int)0);
    ticode.zh.base.整数.到十六进制((int)0);
    ticode.zh.base.整数.到字节((int)0);
    ticode.zh.base.文本.从字符集创建(new char[0]);
    ticode.zh.base.文本.从字节集创建(new byte[0], (String)null);
    ticode.zh.base.文本.拼接文本数组((String[])null, (String)null);
    ticode.zh.base.文本.拼接文本集合((java.util.List<String>)null, (String)null);
    ticode.zh.base.文本.格式化((String)null, (Object[])null);
    ticode.zh.base.长整数.到二进制((long)0);
    ticode.zh.base.长整数.到八进制((long)0);
    ticode.zh.base.长整数.到十六进制((long)0);
    ticode.zh.jvm.Dex类加载器.创建实例((String)null, (String)null, (String)null, (ticode.zh.jvm.Java类加载器)null);
    ticode.zh.jvm.Dex类加载器.取系统类加载器();
    ticode.zh.jvm.GZIP操作.创建GZIP输入流((java.io.InputStream)null);
    ticode.zh.jvm.GZIP操作.创建GZIP输出流((java.io.OutputStream)null);
    ticode.zh.jvm.GZIP操作.创建文件输出流((java.io.File)null);
    ticode.zh.jvm.GZIP操作.压缩字节集(new byte[0]);
    ticode.zh.jvm.GZIP操作.压缩文件((String)null, (String)null);
    ticode.zh.jvm.GZIP操作.解压字节集(new byte[0]);
    ticode.zh.jvm.GZIP操作.解压文件((String)null, (String)null);
    ticode.zh.jvm.GZIP输入流.创建实例((ticode.zh.jvm.输入流)null, (ticode.zh.jvm.解压器)null);
    ticode.zh.jvm.GZIP输入流.创建实例2((ticode.zh.jvm.输入流)null, (ticode.zh.jvm.解压器)null, (int)0);
    ticode.zh.jvm.GZIP输出流.创建实例((ticode.zh.jvm.输出流)null, (ticode.zh.jvm.压缩器)null);
    ticode.zh.jvm.GZIP输出流.创建实例2((ticode.zh.jvm.输出流)null, (ticode.zh.jvm.压缩器)null, (int)0);
    ticode.zh.jvm.Java修饰符工具类.到文本((int)0);
    ticode.zh.jvm.Java修饰符工具类.包含abstract((int)0);
    ticode.zh.jvm.Java修饰符工具类.包含final((int)0);
    ticode.zh.jvm.Java修饰符工具类.包含interface((int)0);
    ticode.zh.jvm.Java修饰符工具类.包含native((int)0);
    ticode.zh.jvm.Java修饰符工具类.包含private((int)0);
    ticode.zh.jvm.Java修饰符工具类.包含protected((int)0);
    ticode.zh.jvm.Java修饰符工具类.包含public((int)0);
    ticode.zh.jvm.Java修饰符工具类.包含static((int)0);
    ticode.zh.jvm.Java修饰符工具类.包含strict((int)0);
    ticode.zh.jvm.Java修饰符工具类.包含synchronized((int)0);
    ticode.zh.jvm.Java修饰符工具类.包含transient((int)0);
    ticode.zh.jvm.Java修饰符工具类.包含volatile((int)0);
    ticode.zh.jvm.Java类.取指定Java类((Object)null);
    ticode.zh.jvm.Java类加载器.取系统类加载器();
    ticode.zh.jvm.UUID.从字节集创建(new byte[0]);
    ticode.zh.jvm.UUID.从文本创建((String)null);
    ticode.zh.jvm.UUID.取随机标识符();
    ticode.zh.jvm.UUID.新建对象((int)0, (int)0);
    ticode.zh.jvm.ZIP操作.创建ZIP输出流((java.io.OutputStream)null);
    ticode.zh.jvm.ZIP操作.创建文件输出流((java.io.File)null);
    ticode.zh.jvm.ZIP操作.压缩文件((String)null, (String)null);
    ticode.zh.jvm.ZIP操作.压缩文件1((ticode.zh.jvm.ZIP输出流)null, (java.io.File)null, (String)null);
    ticode.zh.jvm.ZIP操作.解压单个文件((String)null, (String)null, (String)null);
    ticode.zh.jvm.ZIP操作.解压文件((String)null, (String)null);
    ticode.zh.jvm.ZIP文件.指定编码创建((String)null, (String)null);
    ticode.zh.jvm.ZIP条目.创建新条目((String)null);
    ticode.zh.jvm.ZIP输入流.创建实例((ticode.zh.jvm.输入流)null, (ticode.zh.jvm.解压器)null);
    ticode.zh.jvm.ZIP输入流.创建实例2((ticode.zh.jvm.输入流)null, (ticode.zh.jvm.解压器)null, (int)0);
    ticode.zh.jvm.ZIP输入流.指定编码创建((ticode.zh.jvm.输入流)null, (String)null);
    ticode.zh.jvm.ZIP输出流.创建实例((ticode.zh.jvm.输出流)null, (ticode.zh.jvm.压缩器)null);
    ticode.zh.jvm.ZIP输出流.创建实例2((ticode.zh.jvm.输出流)null, (ticode.zh.jvm.压缩器)null, (int)0);
    ticode.zh.jvm.ZIP输出流.指定编码创建((ticode.zh.jvm.输出流)null, (String)null);
    ticode.zh.jvm.dex文件.实例化((String)null);
    ticode.zh.jvm.压缩器.创建GZIP兼容压缩器((int)0);
    ticode.zh.jvm.压缩输入流.创建实例((ticode.zh.jvm.输入流)null, (ticode.zh.jvm.压缩器)null);
    ticode.zh.jvm.压缩输入流.创建实例2((ticode.zh.jvm.输入流)null, (ticode.zh.jvm.压缩器)null, (int)0);
    ticode.zh.jvm.压缩输出流.创建实例((ticode.zh.jvm.输出流)null, (ticode.zh.jvm.压缩器)null);
    ticode.zh.jvm.压缩输出流.创建实例2((ticode.zh.jvm.输出流)null, (ticode.zh.jvm.压缩器)null, (int)0);
    ticode.zh.jvm.双端队列.从集合创建((ticode.zh.jvm.集合)null);
    ticode.zh.jvm.反射操作.创建实例((String)null, (java.lang.Class[])null, (Object[])null);
    ticode.zh.jvm.反射操作.创建实例2((java.lang.Class)null, (java.lang.Class[])null, (Object[])null);
    ticode.zh.jvm.反射操作.加载Dex文件((android.content.Context)null, (String)null, (String)null);
    ticode.zh.jvm.反射操作.执行方法((String)null, (Object)null, (String)null, (java.lang.Class[])null, (Object[])null);
    ticode.zh.jvm.反射操作.执行方法2((java.lang.Class)null, (Object)null, (String)null, (java.lang.Class[])null, (Object[])null);
    ticode.zh.jvm.反射操作.执行方法3((Object)null, (java.lang.reflect.Method)null, (Object[])null);
    ticode.zh.jvm.反射操作.执行无参方法((String)null, (Object)null, (String)null);
    ticode.zh.jvm.反射操作.执行无参方法2((java.lang.Class)null, (Object)null, (String)null);
    ticode.zh.jvm.反射操作.根据类型寻找字段((String)null, (String)null);
    ticode.zh.jvm.反射操作.根据类型寻找字段2((java.lang.Class)null, (String)null);
    ticode.zh.jvm.反射操作.根据类型寻找字段3((java.lang.Class)null, (java.lang.Class)null);
    ticode.zh.jvm.反射操作.获取字段值((String)null, (Object)null, (String)null);
    ticode.zh.jvm.反射操作.获取字段值2((java.lang.Class)null, (Object)null, (String)null);
    ticode.zh.jvm.反射操作.获取字段值3((Object)null, (java.lang.reflect.Field)null);
    ticode.zh.jvm.反射操作.设置字段值((String)null, (Object)null, (String)null, (Object)null);
    ticode.zh.jvm.反射操作.设置字段值2((java.lang.Class)null, (Object)null, (String)null, (Object)null);
    ticode.zh.jvm.反射操作.设置字段值3((Object)null, (java.lang.reflect.Field)null, (Object)null);
    ticode.zh.jvm.对象输入流.从路径创建((String)null);
    ticode.zh.jvm.对象输出流.从路径创建((String)null);
    ticode.zh.jvm.控制台.取输入小数();
    ticode.zh.jvm.控制台.取输入整数();
    ticode.zh.jvm.控制台.取输入文本();
    ticode.zh.jvm.控制台.取输入浮点数();
    ticode.zh.jvm.控制台.取输入逻辑值();
    ticode.zh.jvm.控制台.取输入长整数();
    ticode.zh.jvm.控制台.是否有下一行();
    ticode.zh.jvm.控制台.输出((Object)null);
    ticode.zh.jvm.控制台.输出格式文本((String)null, (Object[])null);
    ticode.zh.jvm.控制台.输出行((Object)null);
    ticode.zh.jvm.文件.从路径创建((String)null);
    ticode.zh.jvm.文件.新建对象((String)null, (String)null);
    ticode.zh.jvm.文件.新建对象2((java.io.File)null, (String)null);
    ticode.zh.jvm.文件输入流.从路径创建((String)null);
    ticode.zh.jvm.文件输出流.从路径创建((String)null);
    ticode.zh.jvm.正则表达式.正则匹配((String)null, (String)null, (int)0);
    ticode.zh.jvm.正则表达式.正则匹配2((String)null, (String)null, (int)0);
    ticode.zh.jvm.正则表达式.编译((String)null);
    ticode.zh.jvm.线程池.停止固定线程池所有任务();
    ticode.zh.jvm.线程池.停止缓存线程池所有任务();
    ticode.zh.jvm.线程池.提交到固定线程池运行();
    ticode.zh.jvm.线程池.提交到缓存线程池运行();
    ticode.zh.jvm.线程池.等待固定线程池执行完毕();
    ticode.zh.jvm.线程池.等待缓存线程池执行完毕();
    ticode.zh.jvm.线程池.结束提交到固定线程池();
    ticode.zh.jvm.线程池.结束提交到缓存线程池();
    ticode.zh.jvm.线程池.置固定线程池大小((int)0);
    ticode.zh.jvm.缓冲输入流.从路径创建((String)null);
    ticode.zh.jvm.缓冲输出流.从路径创建((String)null);
    ticode.zh.jvm.解压器.创建GZIP兼容解压器();
    ticode.zh.jvm.解压输入流.创建实例((ticode.zh.jvm.输入流)null, (ticode.zh.jvm.解压器)null);
    ticode.zh.jvm.解压输入流.创建实例2((ticode.zh.jvm.输入流)null, (ticode.zh.jvm.解压器)null, (int)0);
    ticode.zh.jvm.解压输出流.创建实例((ticode.zh.jvm.输出流)null, (ticode.zh.jvm.解压器)null);
    ticode.zh.jvm.解压输出流.创建实例2((ticode.zh.jvm.输出流)null, (ticode.zh.jvm.解压器)null, (int)0);
    ticode.zh.jvm.语言环境.新建语言环境((String)null, (String)null);
    ticode.zh.meng.高级适配器.创建适配器((Object)null);
    ticode.zh.meng.高级适配器.创建高级适配器((ticode.zh.jvm.集合)null);
    ticode.zh.meng.高级适配器.高级适配器((ticode.zh.jvm.集合)null);
    简易无障碍.拖动坐标((float)0, (float)0, (float)0, (float)0);
    简易无障碍.点击坐标((float)0, (float)0);
    简易无障碍.申请权限((android.content.Context)null);
  }
}
